## <center> __University of Santo Tomas – Faculty of Engineering Electronics Engineering Department__ </center>

## <center> __ECE 2112: Advanced Computer Programming and Algorithms__ </center>

# <center> __EXPERIMENT 3: PYTHON DATA ANALYSIS (PANDAS)__ </center>

#### Emmanuelle D.G. Miran| 2ECE-C

## **I.** Intended Learning Outcomes

1. Load a CSV dataset into a Pandas DataFrame;
2. Select rows and columns using positional and label-based indexing;
3. Filter records using conditions on a DataFrame column; and
4. Extract a well-defined subset of data without changing the source data.

## **II.** Panda Initialization

In [1]:
import pandas as pd
cars = pd.read_csv("cars.csv")
cars

,Model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

## **III.** Programming Problems

>  ##  **A.** POSITIONAL AND LABEL-BASED SLICING

>After loading **cars**, complete the following operations.<br>
>>**A.** Display the shape and complete list of column names of cars.<br>
>>**B.** Using positional slicing, create cars 6 to 10 containing rows 6 through 10 of the dataset, where the first data row is row 1.<br>
>>**C.** From cars 6 to 10, display only the columns Model, mpg, cyl, hp, and gear, in that order.<br>

>**Requirement:** The row selection in part (b) must use iloc; the column selection in part (c) must use column labels.

> ## Explanation

>>For this programming problem, the first thing we need to do is to initialize the **cars.csv** file into the Panda's dataframe. To do this, we need to use the function ***pd.read_csv()***. This function was accomplished in the previous section of the **PA**.<br><br>
>>To be able to display the shape and complete list of column names of cars, we are to use two different functions. The first function is ***.shape***, which simply returns the dimensions of the dataset given in the **.csv** file. The second function that we will use is ***.columns***, this function allows us to display all of the names of each column from the **.csv** file.<br><br>
>>To create a set of rows from 6 through 10 of the data set, we will use the function ***.iloc[]***. This function allows us to select specific rows and columns from the Data Frame designated by their numerical position. For this specific problem we will be using the function ***cars.iloc[5:10]*** This is because, from what I understand, we were asked to get rows 6 to 10 from the data frame, which would be the equivalent of 5 to 10 in Python because it uses zero-based indexing. We start with 5 in the function because that is the equivalent of 6 from the data frame, and we end at 10 because it tells the function to stop right before that row.<br><br>
>>To tackle the last part, we will use the function ***cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]***. This allows us to display only these specific columns in the specific order that we listed them in. This was only possible to be executed because we defined what **cars_6_to_10** is at the previous requirement.

> ## Code & Outputs

In [2]:
Shape=cars.shape
Shape

(32, 12)

In [3]:
Columns_of_Names = cars.columns
Columns_of_Names

Index(['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='str')

In [4]:
cars_6_to_10 = cars.iloc[5:10]
cars_6_to_10

        Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
5     Valiant  18.1    6  225.0  105  2.76  3.46  20.22   1   0     3     1
6  Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7   Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8    Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9    Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4

In [5]:
cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

>  ##  **B.** MODEL LOOKUP

>Use Boolean indexing on the Model column to answer both requests<br>
>>**A.** Display the complete row for Toyota Corolla.<br>
>>**B.** For Pontiac Firebird, display only Model, mpg, hp, and wt.<br>

>Store the two results in toyota and pontiac, respectively. Do not use a hard-coded row number to locate either model.

> ## Explanation

>>For this programming problem, we were tasked to display the complete row for the Toyota Corolla. To accomplish this we use something called **Boolean Slicing** with the function ***cars[cars['Model'] == 'Toyota Corolla']***. To explain this function, we will break it down into parts. In this function **cars['Model'] == 'Toyota Corolla'** basically checks the **Model** column if any of the individual rows include the word **Toyota Corolla** and it labels this as true and anything else as false. The outer **cars[]** will allow us to display all the rows that were labeled as **True**.<br><br>
>>For the next required problem, it is basically the same as the **Toyota Corolla** problem, but we identify the **Pontiac Firebird** instead, with an added condition where it will only display the columns **Model**, **mpg**, **hp**, and **wt**. This can be done in the same way as the final condition at the previous programming problem; we use the function ***[['Model', 'mpg', 'hp', 'wt']]***.
>>

> ## Code & Outputs

In [6]:
toyota = cars[cars['Model'] == 'Toyota Corolla']
toyota

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

In [7]:
pontiac = cars[cars['Model'] == 'Pontiac Firebird'] [['Model', 'mpg', 'hp', 'wt']]
pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

>  ##  **C.** Multi-Model Subsetting

>Create a DataFrame named selected cars containing only the records for three models: Datsun 710, Lotus Europa, and Ferrari Dino.<br>
>For these records, retain only Model, mpg, cyl, hp, and gear. Select the rows by their model values rather than by row numbers. Display selected cars and its shape. <br>
>**Required check:** The final DataFrame must contain exactly three rows and five columns

> ## Explanation

>>For this programming problem, we were tasked to create a DataFrame named **selected cars** containing three models: Datsun 710, Lotus Europa, and Ferrari Dino. To solve this, we essentially need to redo what we did for the previous programming problem, where we used the function ***cars['Model'] == ' '*** to check if a specific model of a car is in the **Model** column. The only difference here now is that we check for three different models at the same time rather than just one. To accomplish this, we can either simply use the symbol **|** to represent **OR** in the function by, or we can add the function .isin() so we don't have to redo the ***cars['Model'] == ' '*** three times. For this programming problem I will be using **.isin()**.<br><br>
>>To retain only the **Model**, **mpg**, **cyl**, **hp**, and **gear**. We will use the function ***[["Model", "mpg", "cyl", "hp", "gear"]]*** which is similar to the function we used on both the final conditions of the last two programming problems.<br><br>
>>To do the required check we can simply use the function ***.shape***.

> ## Code & Outputs

In [8]:
selected_cars = cars[cars['Model'].isin(['Datsun 710', 'Lotus Europa', 'Ferrari Dino'])] [["Model", "mpg", "cyl", "hp", "gear"]]
selected_cars

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

In [9]:
selected_cars.shape

(3, 5)